config/routes.rb
Workoutgen::Application.routes.draw do
  devise_for :users

  resources :exes
  resources :workouts

  root :to => 'pages#home'

end

app/models/ex.rb
#we use this to get the image
require 'open-uri'
class Ex < ActiveRecord::Base
  attr_accessible :category, :description, :name, :url, :user_id, :asset, :image_url
  has_attached_file :asset,
  									:url => "/assets/exes/:id/:basename.:extension",
  									:path => ":rails_root/public/assets/exes/:id/:basename.:extension",
  									:default_url => "/assets/noimage.jpg"
  validates :name, :category, :presence => true
  belongs_to :user


  def image_url
  	if !self[:image_url].empty? #there's a link to a picture
			return self[:image_url] #return that
		else
			return asset.url #return uploaded image
		end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :id
  # attr_accessible :title, :body

  has_many :exes

  def has_exes(cat)
  	my_exes = Ex.where(:category => cat, :user_id => self.id)
  	!my_exes.empty?
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :cardio, :strength, :stretch, :total, :user_id
  validates :cardio,  :strength, :stretch, :presence => true,
  																								:numericality => true
  																								{ :only_integer => true,
  																									:greater_than => -1 }

  def cardios
    if cardio > 0
 	    cardios = Ex.where(:category => 'cardio', :user_id => self.user_id)
      item = cardios[rand(cardios.count)]
      [item]
    else
      []
    end
    # (1..cardio).to_a.map do
    #   cardios[rand(cardios.count)]
    # end
    #this needs to return an array of one exercise
  end

  def strengths
  	strengths = Ex.where(:category => 'strength', :user_id => self.user_id)
		(1..strength/2).to_a.map do
			strengths[rand(strengths.count)]
		end
	end

	def stretches
		stretches = Ex.where(:category => 'stretch', :user_id => self.user_id)
		(1..stretch/2).to_a.map do
			stretches[rand(stretches.count)]
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/exes_controller.rb
class ExesController < ApplicationController

before_filter :authenticate_user!, :except => [:index, :show]

	def index
		if current_user
			@exes = Ex.where(:user_id => current_user.id)
		else
			redirect_to new_user_session_path
		end
	end

	def new
		@ex = Ex.new(:user_id => current_user.id)
	end

	def create
		@ex = Ex.new(params[:ex])
		@ex.user = current_user
		@ex.save

    if @ex.save
    	flash[:notice] = "Exercise added to list."
      redirect_to exes_path
    else
      flash[:alert] = "Exercise must have a name and a category."
      render :action => "new"
    end
	end

	def show
		@ex = Ex.find(params[:id])
	end

	def edit
		@ex = Ex.find(params[:id])
	end

	def update
		@ex = Ex.find(params[:id])
		if @ex.update_attributes(params[:ex])
			@ex.save
			flash[:notice] = "Exercise updated!"
			redirect_to exes_path
		else
    	flash[:alert] = "Exercise must have a name and a category."
      render :action => "new"
		end
	end

	def destroy
		@ex = Ex.find(params[:id])
		@ex.destroy

		if @ex.destroy
			flash[:notice] = "Exercise deleted!"
			redirect_to exes_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		#If you lived here you'd be home now.
	end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

	def index
		@workout = Workout.new(params[:workout])
		@workout.user_id = current_user.id

		if not @workout.valid?
			flash[:alert] = "Please put a number in each field, even if it's zero. Thanks."
			redirect_to new_workout_path
		end
	end

	def new
		@workout = Workout.new
		if current_user
			@workout.user_id = current_user.id
		else
			redirect_to new_user_session_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exes_helper.rb
module ExesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper

end

app/views/exes/_form.html.erb
<p>Add an exercise</p>
<%= form_for [(@ex)], :html => { :multipart => true } do |f| %>

	<p>
		<%= f.label :name, "Name (required)" %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :category, "Category (required)" %>
		<%= f.radio_button(:category, 'cardio', :id => 'cardio') %> Cardio
		<%= f.radio_button(:category, 'strength', :id => 'strength') %> Strength
		<%= f.radio_button(:category, 'stretch', :id => 'stretch') %> Stretch
	</p>
<br>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :asset, "You can upload a photo if you'd like"%>
		<%= f.file_field :asset %>
	</p>

	<p>
		<%= f.label :image_url, "Or you can add the url of a photo" %>
		<%= f.text_field :image_url %>
	</p>

	<p>
		<%= f.label :url, 'You can add the url of a website' %>
		<%= f.text_field :url %>
	</p>

	<p>
		<%= f.submit "Save" %>
	</p>

<% end %>

app/views/exes/edit.html.erb
<%= render "form" %>

app/views/exes/index.html.erb
<div><h4>Exercises</h4></div>
<p>
<% if @exes.empty? %>
	You have no exercises. Please add some.
<% end %>
<div class='btn'><%= link_to "Add exercise", new_ex_path %></div>
</p>

<div>
	<ul>
		<% @exes.each do |ex| %>
			<li><%= link_to ex.name, ex%></li>
		<% end %>
	</ul>
</div>

app/views/exes/new.html.erb
<%= render "form" %>

app/views/exes/show.html.erb
<strong><%= @ex.name %></strong><br>
<%= @ex.description %><br>
<%= @ex.category %><br>
<%= image_tag(@ex.image_url, :width => '400') %><br>
<%= link_to @ex.url, @ex.url, :target => '_blank' %><br>
<%= link_to "edit", edit_ex_path %> <%= link_to "delete", ex_path, :method => :delete, :confirm => "Are you sure?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workoutgen" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'assets/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body id="body">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Random Workout Generator</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Generate Workout", new_workout_path  %></li>
              <li><%= link_to "Exercises", exes_path  %></li>
              <% if user_signed_in? %>
                <li>Signed in as <%= current_user.email %></li>
                <li><%= link_to "Sign out", destroy_user_session_path,
                    :method => :delete %></li>
                <% else %>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span8" id="main">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer class="footer">
        <p>&copy; Calico Goodrich 2013</p>
      </footer>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>



  </body>
</html>

app/views/pages/home.html.erb
<p>Hey, you're looking foxy this morning.</p>
<p> But you know what? You still need to get off your doughy ass and do some physical activity. So go do it!</p>
<p> No excuses! Right now!</p>
<br>
<div class="btn">
<%= link_to "Generate Workout", new_workout_path %>
</div>

app/views/workouts/_form.html.erb
<%= form_for @workout, :method => :get do |f| %>
	<p>
		Good morning!
	</p>
	<p>
		Please enter the amount of time you would like for each category.
	</p>
	<br>
	<p>
		<%= f.label :cardio %>
		<%= f.text_field :cardio %>
	</p>
	<p>
		<%= f.label :strength, "Strength Training" %>
		<%= f.text_field :strength %>
	</p>
	<p>
		<%= f.label :stretch, "Stretching" %>
		<%= f.text_field :stretch %>
	</p>
	<p>
		<%= f.submit "Generate" %>
	</p>

<% end %>

app/views/workouts/index.html.erb
<p><h4>Here is your workout. Enjoy!</h4></p>
<br>

<div>
<% if current_user.has_exes(:cardio) %>
	<ul>
			<% @workout.cardios.each do |ex| %>
			<li>
			<%= image_tag(ex.image_url, :width => '150') %>
			<span class="ex_name">
			<%= link_to ex.name,
				:controller => 'exes', :action => 'show', :id => ex.id %>
			</span>
			</li>
		<% end %>
	</ul>
<% else %>
	<p>You don't have any cardio exercises yet.
		 You can add some <%= link_to 'here', exes_path %></p>
<% end %>
</div>

<div>
<% if current_user.has_exes(:strength) %>
	<ul>
		<% @workout.strengths.each do |ex| %>
			<li>
			<%= image_tag(ex.image_url, :width => '150') %>
			<span class="ex_name">
			<%= link_to ex.name,
				:controller => 'exes', :action => 'show', :id => ex.id %>
			</span>
			</li>
		<% end %>
	</ul>
<% else %>
	<p>You don't have any strength exercises yet. You can add some <%= link_to 'here', exes_path %></p>
<% end %>
</div>

<div>
<% if current_user.has_exes(:stretch) %>
	<ul>
		<% @workout.stretches.each do |ex| %>
			<li>
			<%= image_tag(ex.image_url, :width => '150') %>
			<span class="ex_name">
			<%= link_to ex.name,
				:controller => 'exes', :action => 'show', :id => ex.id %>
			</span>
			</li>
		<% end %>
	</ul>
<% else %>
	<p>You don't have any stretching exercises yet. You can add some <%= link_to 'here', exes_path %></p>
<% end %>
</div>

<div>
<% if current_user.has_exes(:cardio) %>
	<ul>
			<% @workout.cardios.each do |ex| %>
			<li>
			<%= image_tag(ex.image_url, :width => '150') %>
			<span class="ex_name">
			<%= link_to ex.name,
				:controller => 'exes', :action => 'show', :id => ex.id %>
			</span>
			</li>
		<% end %>
	</ul>
<% end %>
</div>


<div>
	This workout sucks. <%= link_to "Give me a new one.", workouts_path(:workout => params[:workout]), :method => 'get' %>
</div>

app/views/workouts/new.html.erb
<%= render 'form' %>